INSERT INTO plans (
  id,
  name,
  description,
  price_monthly,
  price_annual,
  original_price_monthly,
  original_price_annual,
  currency,
  dodo_product_id,
  dodo_product_id_annual,
  is_popular,
  discount_percent,
  trial_days,
  max_schedules,
  max_integrations,
  max_exports_per_month,
  max_webhooks,
  max_api_keys,
  feature_schedules,
  feature_exports,
  feature_integrations,
  feature_webhooks,
  feature_api_access,
  feature_priority_support,
  limits,
  features,
  not_included,
  created_at
) VALUES

-- STARTER
(
  'starter',
  'Starter',
  'Reliable automation for essential Amazon data exports.',
  9,
  86,
  19,
  182,
  'USD',
  'pdt_wjiekEq5pS3BsWyKpMhVN',
  'pdt_GudeJz71mLiiRF3Ygw9iS',
  false,
  20,
  14,
  5,
  0,
  -1,
  0,
  1,
  true,
  true,
  false,
  false,
  false,
  false,
  '{
    "accounts": 1,
    "schedules": 5,
    "apiCredits": 5000,
    "marketplaces": 2
  }'::jsonb,
  '[
    "1 Amazon Account",
    "5,000 Credits per month",
    "Up to 2 Marketplaces",
    "Manual, Daily and Weekly schedules",
    "CSV, Excel and JSON exports",
    "All tools included"
  ]'::jsonb,
  '[
    "Integrations",
    "Priority Support",
    "Advanced Scheduling"
  ]'::jsonb,
  now()
),

-- PROFESSIONAL
(
  'professional',
  'Professional',
  'Continuous automation for sellers who rely on data daily.',
  24,
  230,
  39,
  374,
  'USD',
  'pdt_yN4GRiYmTA1SZOA1Kql3h',
  'pdt_CZCyDnVLqmLLJMIs8YKFd',
  true,
  20,
  14,
  25,
  5,
  -1,
  0,
  1,
  true,
  true,
  true,
  false,
  false,
  true,
  '{
    "accounts": 1,
    "schedules": 25,
    "apiCredits": 25000,
    "marketplaces": -1
  }'::jsonb,
  '[
    "1 Amazon Account",
    "25,000 Credits per month",
    "All Marketplaces",
    "Hourly, Daily, Weekly and Monthly schedules",
    "Up to 25 active schedules",
    "CSV, Excel and JSON exports",
    "Google Sheets and Drive integration",
    "Telegram and Discord notifications",
    "Priority Support",
    "All tools included"
  ]'::jsonb,
  '[
    "Slack notifications",
    "Unlimited schedules"
  ]'::jsonb,
  now()
),

-- BUSINESS
(
  'business',
  'Business',
  'High-volume automation without friction or micromanagement.',
  49,
  470,
  79,
  758,
  'USD',
  'pdt_nIPtxODpgt0F1376c5nNI',
  'pdt_NDqCzb40Ck8sQkB4nVl1V',
  false,
  20,
  14,
  -1,
  -1,
  -1,
  0,
  1,
  true,
  true,
  true,
  false,
  false,
  true,
  '{
    "accounts": 1,
    "schedules": -1,
    "apiCredits": 100000,
    "marketplaces": -1
  }'::jsonb,
  '[
    "1 Amazon Account",
    "100,000 Credits per month",
    "All Marketplaces",
    "Unlimited schedules",
    "All scheduling frequencies",
    "Run Now override on schedules",
    "CSV, Excel and JSON exports",
    "Extended export history",
    "Google Sheets and Drive integration",
    "Telegram, Discord and Slack notifications",
    "Priority Support",
    "All tools included"
  ]'::jsonb,
  '[]'::jsonb,
  now()
);
